name: targets
author: Jack Thakar <jack@jackthakar.com>
homepage: http://github.com/dart-targets/targets
version: 0.8.0-beta
description: Assignment manager for high school CS classes
environment:
    sdk: ">=1.9.0 <2.0.0"
dependencies:
    archive: ">=1.0.19 <2.0.0"
    http: ">=0.11.1+3 <0.12.0"
    args: ">=0.12.0+2 <0.13.0"
    crypto: "^0.9.0"
dev_dependencies:
    test: "^0.12.3+8"
executables:
    targets: targets