name: targets
author: Jack Thakar <jack@jackthakar.com>
homepage: http://github.com/dart-targets/targets
version: 0.6.0
description: Simple assignment manager and autograder for Dart
dev_dependencies:
  browser: ">=0.10.0+2 <0.11.0"
executables:
    targets: targets