name: targets
author: Jack Thakar <jack@jackthakar.com>
homepage: http://github.com/dart-targets/targets
version: 0.8.0-experimental
description: Simple assignment manager and autograder
dependencies:
    archive: ">=1.0.19 <2.0.0"
    http: ">=0.11.1+3 <0.12.0"
    args: ">=0.12.0+2 <0.13.0"
    crypto: "^0.9.0"
    redstone_mapper: "^0.1.13"
dev_dependencies:
    browser: ">=0.10.0+2 <0.11.0"
    test: "^0.12.3+8"
dependency_overrides:
    # resolves conflict between test and redstone_mapper
    analyzer: ">=0.23.0 <=0.26.0-alpha.0"
executables:
    targets: targets